# Generated by Django 4.0 on 2022-01-02 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pet_category', models.CharField(choices=[('Dog', 'Dog'), ('Cat', 'Cat'), ('Rabbit', 'Rabbit')], max_length=50)),
                ('pet_name', models.CharField(max_length=10)),
                ('pet_age', models.CharField(choices=[('Upto 6 months', 'Upto 6 months'), ('6-8 months', '6-8 months'), ('1.5-3 years', '1.5-3 years'), ('3 years or more', '3 years or more')], max_length=50)),
                ('pet_bread', models.CharField(max_length=10)),
                ('pet_gender', models.CharField(choices=[('male', 'male'), ('female', 'female')], max_length=10)),
                ('pet_vaccinated', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='', max_length=3)),
                ('pet_neutered', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='', max_length=3)),
                ('pet_sprayed', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='', max_length=3)),
                ('pet_good_kids', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='', max_length=3)),
            ],
        ),
    ]
