# Generated by Django 4.0 on 2022-01-02 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='pet_image',
            field=models.ImageField(default='', upload_to='pePet_pic'),
        ),
    ]
