# Generated by Django 4.0 on 2022-01-02 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pet', '0002_pet_pet_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='pet_image',
            field=models.ImageField(blank=True, default='', null=True, upload_to='pePet_pic'),
        ),
    ]
