# Generated by Django 4.0.1 on 2022-01-06 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pet', '0004_pet_pet_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='pet_status',
            field=models.CharField(choices=[('adopted', 'adopted'), ('not_adopted', 'not_adopted')], default='not_adopted', max_length=40),
        ),
    ]
